// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzafiisyhrazwgqbomcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6YWZpaXN5aHJhendncWJvbWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTc4MjksImV4cCI6MjA2NzA5MzgyOX0.FI6bqRV1eYBsPVZ2yWbd8HhpHAaiObuRXLZfudOhTQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});